version: "3.8"
networks:
  default:
    name: dev
    external: true
services:
  api:
    container_name: microservice-auth-jwt
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: unless-stopped 
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.microservices-general-auth.entrypoints=http"
      - "traefik.http.routers.microservices-general-auth.rule=Host(`microservices-general-auth.alfredjmg.dev`)"
      - "traefik.http.middlewares.microservices-general-auth-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.microservices-general-auth.middlewares=microservices-general-auth-https-redirect"
      - "traefik.http.routers.microservices-general-auth-secure.entrypoints=https"
      - "traefik.http.routers.microservices-general-auth-secure.rule=Host(`microservices-general-auth.alfredjmg.dev`)"
      - "traefik.http.routers.microservices-general-auth-secure.tls=true"
      - "traefik.http.routers.microservices-general-auth-secure.service=microservices-general-auth"
      - "traefik.http.services.microservices-general-auth.loadbalancer.server.port=3005"
      - "traefik.docker.network=dev"